### PR TITLE
Implemented dark mode

### PR DESCRIPTION
**Pull request by mr-manuel**
Tested with this Venus OS versions:
* v2.93
* v.294
* v3.00~36
* v3.00~39
* v3.00~42

Fixes https://github.com/kwindrem/GuiMods/issues/151

### CODE REVIEW

**Comment by mr-manuel** [comment]
Can be tested by inserting manually in the package manager or by downloading the [latest release](https://github.com/mr-manuel/venus-os_GuiMods/releases) from my repository.

grafik

**Comment by Eagle383** [comment]
Like what I'm seeing, I was messing around with dark mode and bravo. I didn't know if I could ask if you could apply your settings to one more page, mainly if there was a way to have white text on the tank screen the GuiMods provides. 
image

**Comment by mr-manuel** [comment]
Is the color scheme default or provided by my dark mode? What does the light mode like of this page?

@kwindrem how can I access this page without tanks?

**Comment by kwindrem** [comment]
Not sure what allows the tanks overview to appear without tanks.

**Comment by Eagle383** [comment]
To get tanks without tanks 
General > Demo Mode > Boat / Motor Home Demo 1
To get this view
Display Language > Show Tanks OverView

I have not modified the color scheme from what comes with the Venus OS just applied Dark mode.
image

**Comment by kwindrem** [comment]
I looked at a tiny bit of your changes and noticed that you are testing for darkMode.value but not if it is valid. This may cause the gui to crash or at least default to dark mode.

I usuallly set a property if the dBus parameter is tested mote than once:


 	property VBusItem darkModeItem: VBusItem { bind: "com.victronenergy.settings/Settings/GuiMods/DarkMode" }

	 property boot darkMode: darkMode.valid && darkMode.value == 1

Also, it makes it much easier to maintain if you mark your changes in the file with a comment like

//// GuiMods — DarkMode

**Comment by teefixx** [comment]
hi
thank you for implementing dark mode.
could you have a look at the cell volts, the visibility is not so good...
have a look at the comparison:

image

image

would be great if that could be improved a little bit.
thank you

**Comment by mr-manuel** [comment]
@teefixx this is already fixed, but not released ;-)

**Comment by mr-manuel** [comment]
> Also, it makes it much easier to maintain if you mark your changes in the file with a comment like
>
> //// GuiMods — DarkMode

Is it enough when I place it on non obvious elements like

```python
////// GuiMods — DarkMode
    SvgRectangle
    {
        id:inverterForeground
        width: 126
        height: 132.6
        radius: 3
        color: "#000000"
        opacity: !darkMode ? 0 : 0.5
    }
```

and do not add it on obvious elements like this?

```python
    Text
    {
        anchors
        {
            horizontalCenter: multi.horizontalCenter; horizontalCenterOffset: -6.7
            verticalCenter: multi.verticalCenter; verticalCenterOffset: 5
        }
        horizontalAlignment: Text.AlignHCenter
        width: 10
        wrapMode: Text.WrapAnywhere
        color: !darkMode ? "white" : "#e1e1e1"
        font {pixelSize: 14; bold: true}
        text: inverterModeText ()
        lineHeightMode: Text.FixedHeight
        lineHeight: 12
        visible: inverterMode.valid
    }
```

It should already be clear, that the color is affected by the dark mode. But, if you want I will add it anyways. Please let me know.

**Comment by Eagle383** [comment]
Downloaded the patch tank screen looks good now. Appreciate it

**Comment by mr-manuel** [comment]
I added

```ql
////// GuiMods — DarkMode
```

for every line that contains dark mode modifications except the line is right after the previus line with modifications.

**Comment by kwindrem** [comment]
FYI, I just made a small change to GuiMods. A previous merge didn't work. That change involved temperature display for alternators. Files changed: DcSystemRow.qml, DetailAcCharger.qml, DetailAlternator.qml, DetailDcSystem.qml, DetailMotorDrive.qml, DetailWindGen.qml. And of course version and changes.

**Comment by mr-manuel** [comment]
I solved the conflict

**Comment by kwindrem** [comment]
I've got your Dark Mode changes merged into main. Very well done and many thanks. The dimming of the gauge bars seems a bit unnecessary but let's see what others think.

I'm thinking about adding a DarkMode switch to the tool bar at the bottom of the screen. The toggle would appear in the middle of the bar between Pages and Menu. There is no way to access this from the hard buttons since there's no hard button for a center click. A CCGX and a remote console without touch would need to use the Dark Mode switch in the Display and Language menu. This would also offset the up/down indicators.

Another approach would be to base the switch between light and dark modes on time of day like Mac OS and iOS does. That might minimize the user interaction with the switch.

Comments?

**Comment by kwindrem** [comment]
Here's the light/dark mode switch in the tool bar:
Screen Shot 2023-05-19 at  12 59 45 PM

Comments?

**Comment by mr-manuel** [comment]
Nice. I like that button.

Victron told in the post linked at top, that they are already working on a new GUI with a dark mode. Maybe it is also time related.

If you want to make it time related, then it would be better to calculate sunrise/sunset based on GPS position or timezone for dakr/light? That would be super cool!

**Comment by kwindrem** [comment]
Yes, I've been asked to comment on the new GUI. Can't say anything here but it does have an Auto mode for dark/light. I don't think the code exists to control it yet however.

I'm going to leave this as is with a manual toggle for now at least.

Again, thanks for all your great work.

**Comment by kwindrem** [comment]
I'm not seeing any changes to the "hard buttons" panel in the remote console. I seem to remember this dimmed in one of your screen shots. I've rebooted and cleared my browser's cache but didn't seem to make any difference.

**Comment by mr-manuel** [comment]
The hard buttons depend on the system scheme. When you enable darkmode on your device it switches automatically.

**Comment by kwindrem** [comment]
Got it. Thanks.

**Comment by kaldi-de** [comment]
I've made changes in my dark mode theme to look more "modern". Maybe you can use this as a template... (in the victron-communiy my username is "itsme"...)
image

**Comment by mr-manuel** [comment]
I will not make further changes, since Victron has planned a new GUI as stated in the linked post at the top.

**Comment by gainestr** [comment]
Further changes to dark mode or Guimods?On May 27, 2023, at 2:49 AM, Manuel ***@***.***> wrote:﻿
I will not make further changes, since Victron has planned a new GUI as stated in the linked post at the top.

**Comment by kwindrem** [comment]
Future feature development will be considered while new GUI development is in progress. The fate of GuiMods as an enhancement to the new GUI is yet to be determined. We will have to see what the new stock GUI provides.

**Pull request merged**
