### PR TITLE
Add alternator to Generator Page

### PR DESCRIPTION
**Pull request by iNotMario**
This may or may not be the ideal way to do this.
But my generator _is_ an alternator, and naturally i'd like it to show up here...

Notably, i have not tested this with a "genset".

### CODE REVIEW

**Comment by kwindrem** [comment]
I understand and will attempt to support a DC generator coming in through a DC meter programmed as Alternator.

ObjectAcConnection expects power and other parameters from signal or multiple phase AC sources so I’m guessing you probably won’t see any parameters using sys.alternator as that object’s source. The alternator parameters use a different parameter path.

What I would probably do is create a user preference to select what’s shown in what is now the generator AC input tile and format it based on the source (AC genes or DC alternator). Make sense?

**Comment by iNotMario** [comment]
I may not have been clear that this is tested and does work. (I am currently running this code on my GX) When i said i hadn't tested it with a genset, i mean i haven't tested with an AC generator - though it should work same as before.

What i did here was take snippets from the Alternator Detail page and add it to the generator page. It doesn't use the "OverviewAcValuesEnhanced". Instead it uses a TileText with EnhFmt.formatVBusItem.

If somebody has an AC Generator, the old code is still there and it should show that information as it did before.
If somebody has _both_, they should both appear, one on top of the other.

I'll close the pull request if you want to do it another way. Figured i'd offer what works for my use case.

**Comment by kwindrem** [comment]
I'll look your changes over again. If there is space in the tile for both I'll leave it mostly as you have done but do want to add a user preference so that the alternator doesn't show up in the Generator Overview if it is not part of the generator solution.

Thanks for your work.

**Comment by kwindrem** [comment]
I looked at the existing power tile. It currently shows the power gauge, plus power, voltage, current, frequency and the input current limit. For single phase, each is on a separate line. For multiple phases, leg power, voltage and current are combined on the same line and frequency and current limit share a line. So there isn't space to show the DC generator information at the same time.

The snippet you took from the alternator tile on the Complex page only shows power gage and power number as that's all that is shown for any tile on the Complex flow. The Generator Overview should probably also show voltage and current for consistency.

That suggests one of two options:
1) show only power gauge and power number for both the AC and DC generator. There would probably not be room to show individual leg powers for the generator AC input.

2) show EITHER the generator AC input OR the generator DC input (alternator).

3) I could alternate between AC source and DC source if both were present.

Comments?

**Comment by kwindrem** [comment]
I have implemented this a different way. Please check out v7.17~1.
It can be accessed by switching the GitHub branch/tag to "beta".
I display the alternator on the Generator Overview and on the GuiMods Simple Overview
There's a new GuiMods option to enable it. Consult the ReadMe for more details.

Please let me know if this works for you.

**Pull request closed without merging**
